config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'

  get "job/:id" => "jobs#show_public", as: "show_job"

  post "applications/:id" => "applications#create"
  get "application/edit/:id" => "applications#edit", as: "application_approval"
  get "jobs/bizowner" => "jobs#bizowner"

  # AUTHENTICATION
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  # Users - custom routes for users, registration, profile, editing etc
  get "register" => "users#new"
  post "users" => "users#create"
  get "profile" => "users#show"
  get "profile/edit" => "users#edit"
  put "profile" => "users#update"
  patch "profile" => "users#update"
  patch "users/:id" => "users#update"
  resources :users, only: [:index, :destroy] do
    patch 'admin' => "users#toggle_admin", on: :member
  end

  # Jobseekers - custom routes for job seekers
  get "jobseeker/register-profile" => "jobseekers#new"
  post "jobseeker" => "jobseekers#create"
  get "jobseeker/profile/edit" => "jobseekers#edit", as: "edit_job_profile"
  get "jobseeker/profile/:id" => "jobseekers#show_public", as: "show_seeker"
  get "jobseeker/profile" => "jobseekers#show"
  put "jobseeker/:id" => "jobseekers#update"
  patch "jobseeker.:id" => "jobseekers#update"

  # Bizowners - custom routes for biz owners
  get "business/register-profile" => "bizowners#new", as: "bizowner_register"
  post "bizowners" => "bizowners#create"
  get "business/edit" => "bizowners#edit"
  get "business/profile/:id" => "bizowners#show_public", as: "show_business"
  get "business/profile" => "bizowners#show"
  put "business/profile" => "bizowners#update"
  patch "business/profile" => "bizowners#update"
  post "business/profile" => "bizowners#update"

  resources :jobseekers_reviews
  resources :bizowners_reviews
  resources :applications
  resources :users
  resources :bizowners
  resources :jobs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
  belongs_to :bizowner
  has_many :applications, dependent: :destroy

  #VALIDATIONS
  validates :bizowner_id,
  presence: true

  before_save :downcase_fields

  def downcase_fields
    self.company_name.downcase!
    self.job_title.downcase!
    self.job_description.downcase!
    self.address.downcase!
    self.industry.downcase!
  end

  def self.search(search,type)
    if search
      case type
      when "address"
        where('address LIKE ?', "%#{search}%")
      when "company_name"
        where('company_name LIKE ?', "%#{search}%")
      when "job_title"
        where('job_title LIKE ?', "%#{search}%")
      else
        scoped
      end
    else
      all
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :is_authenticated, except: [:index]
  helper_method :sort_column, :sort_direction

  # GET /jobs
  # GET /jobs.json
  def index
    params.permit!
    #Hack way to resolve permit problem.
    # @jobs = Job.all
    # @jobs = Job.search(params[:search],params[:fieldtype]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])


    # search(params[:search],params[:fieldtype]).

    @jobs = Job.search(params[:search],params[:fieldtype]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 5)

    @map_hash = Gmaps4rails.build_markers(@jobs) do |job, marker|
      marker.lat job.latitude
      marker.lng job.longitude
      marker.infowindow job.company_name
    end
  end

  def bizowner
    params.permit!
    @bizowner = current_user.bizowner
    @jobs = current_user.bizowner.jobs.paginate(:page => params[:page], :per_page => 5)
  end

  def show_public
    @job = Job.find_by(id: Application.find_by(id: params[:id]).job_id)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find params[:id]
    unless @current_user.is_admin || Bizowner.find_by(user_id: session[:user_id]).id == @job.bizowner_id
      flash[:notice] = "You do not have permission to edit jobs that do not belong to you!"
      redirect_to root_path
      return
    end
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.update(bizowner_id: Bizowner.find_by(user_id: current_user.id).id)
    @job.update(status: true)
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        puts "job params is ", job_params.inspect ,"@job is ", @job.inspect
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    if @current_user.is_admin || Bizowner.find_by(user_id: session[:user_id]).id == @job.bizowner_id
      @job.destroy
      respond_to do |format|
        format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      flash[:notice] = "You do not have permission to edit listings that do not belong to you!"
      redirect_to root_path
      return
    end
  end

  private

  def sort_column
    Job.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_params
    params.require(:job).permit(:company_name, :job_title, :job_description, :address, :industry, :vacancy, :wage_per_hour, :job_start_date, :job_end_date)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
end
end

app/views/jobs/_form.html.erb
<%= form_for(@job, html: { class: "form-horizontal", role: "form" }) do |f| %>
<% if @job.errors.any? %>
<div class="alert alert-danger alert-dismissable" role="alert">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h4><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h4>

  <ul>
    <% @job.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :"company_name", class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :company_name, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :job_title, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :job_title, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :job_description, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_area :job_description, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :"address", class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :address, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :industry, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :industry, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :vacancy, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.number_field :vacancy, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :hourly_wage, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.number_field :wage_per_hour, :step =>0.1 , class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :start_date, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.date_field :job_start_date, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :end_date, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.date_field :job_end_date, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-md-10">
    <br><%= f.submit class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/jobs/bizowner.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h1>Jobs @ <%= @bizowner.name %></h1>
</div>

<div class = "container">

  <div class="table-responsive">
    <table class="table-striped">
      <thead class="thead-inverse">
        <tr>
          <th><%= sortable "job_title"%></th>
          <th><%= sortable "company_name"%></th>
          <th><%= sortable "address"%></th>
          <th><%= sortable "industry"%></th>
          <th><%= sortable "hourly_wage"%></th>
          <th><%= sortable "start_date"%></th>
          <th><%= sortable "end_date"%></th>
          <th></th>
          <% if current_user %>
          <% if current_user.is_admin %>
          <th colspan="2"></th>
          <% end %>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, @jobs) do |job| %>
        <td><%= link_to job.job_title.capitalize, job_path(job) %></td>
        <td><%= link_to job.company_name.capitalize, show_business_path(job.bizowner_id) %></td>
        <td><%= job.address.capitalize %></td>
        <td><%= job.industry.capitalize %></td>
        <td>$<%= job.wage_per_hour %>0</td>
        <td><%= job.job_start_date %></td>
        <td><%= job.job_end_date %></td>

        <td><%= link_to 'Show', job %></td>
        <% if current_user %>
        <% if current_user.is_admin %>
        <td><%= link_to 'Edit', edit_job_path(job), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <% end %>
        <% end %>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @jobs %>

    <br>
    <% if current_user %>
    <% if current_user.is_biz %>
    <%= link_to 'See All Jobs', jobs_path %> |
    <%= link_to 'New Job', new_job_path %>
    <% end %>
    <% end %>

  </div>

</div>

app/views/jobs/edit.html.erb
<div class="page-header">
  <h1>Edit job</h1>
</div>

<% if current_user.is_biz %>
<%= render 'form' %>
<% end %>

app/views/jobs/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyCZzwCvTDriQgX_bFx2nC6Lbphm2iToO4k"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->



<div id="map"></div>


<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @map_hash.to_json %>);
  handler.bounds.extendWith(markers);

  // _.each(markers, function(marker){
  //        google.maps.event.trigger(marker.getServiceObject(), 'click');
  //      });

  handler.fitMapToBounds();

  if(navigator.geolocation)
  navigator.geolocation.getCurrentPosition(displayOnMap);
});

function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude,
    picture: {
      url: "http://wfarm1.dataknet.com/static/resources/icons/set25/d3b5a956e40.png",
      width:  36,
      height: 36
    },
    infowindow: "Your Current Location!"
  });
  handler.map.centerOn(marker);
  // marker.infowindow.open(Gmaps.map.map, marker
  // Cant get infowindow to open byitself
};
</script>



<div class="container">
  <p id="notice"><%= notice %></p>


  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>

  <br/>
  <div class="search_job_bar">
    <%= form_tag jobs_path, :method => 'get', :id => "jobs_search" do %>
    <p>
      <%= text_field_tag :search, params[:search], class: 'search-form-control', placeholder: 'Search for...' %>
      <%= select_tag "fieldtype", options_for_select([ "address", "company_name", "job_title" ], "address") %>
      <%= submit_tag "SEARCH", class: "btn btn-default" %>
    </p>
  </div>

  <div class="page-header">
    <br/><h3 id ="show_all_jobs">Showing all Jobs</h3>
  </div>


  <% end %>

  <div class ="jobs-table-border">

    <table class="table-striped">
      <thead class="thead-inverse">
        <tr>
          <th><%= sortable "job_title"%></th>
          <th><%= sortable "company_name"%></th>
          <th><%= sortable "address"%></th>
          <th><%= sortable "industry"%></th>
          <th><%= sortable "hourly_wage"%></th>
          <th><%= sortable "start_date"%></th>
          <th><%= sortable "end_date"%></th>
          <th></th>
          <% if current_user %>
          <% if current_user.is_admin %>
          <th colspan="2"></th>
          <% end %>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, @jobs) do |job| %>
        <td><%= link_to job.job_title.capitalize, job_path(job) %></td>
        <td><%= link_to job.company_name.capitalize, show_business_path(job.bizowner_id) %></td>
        <td><%= job.address.capitalize %></td>
        <td><%= job.industry.capitalize %></td>
        <td>$<%= job.wage_per_hour %>0</td>
        <td><%= job.job_start_date %></td>
        <td><%= job.job_end_date%></td>

        <td><%= link_to 'Apply now!', job, class: "btn btn-info" %></td>
        <% if current_user %>
        <% if current_user.is_admin %>
        <td><%= link_to 'Edit', edit_job_path(job), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger"%></td>
        <% end %>
        <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= will_paginate @jobs %>


  <br>
  <% if current_user %>
  <% if current_user.is_biz %>
  <%= link_to 'See My Jobs', jobs_bizowner_path %> |
  <%= link_to 'New Job', new_job_path %>
  <% end %>
  <% end %>


</div>

app/views/jobs/new.html.erb
<br>
<div class="page-header">
  <h1>Post New Job</h1>
</div>

<% if current_user.is_biz %>
<%= render 'form' %>
<% end %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h1><%= @job.job_title.capitalize %> @ <%= @job.company_name.capitalize %></h1>
</div>

<div class="col-md-2">
  <br/><strong>Address:</strong>
</div>
<div class="col-md-10">
  <br/><%= @job.address.capitalize %>
</div>

<div class="col-md-2">
  <br/><strong>Company Name:</strong>
</div>
<div class="col-md-10">
  <br/><%= @job.company_name.capitalize %>
</div>

<div class="col-md-2">
  <br/><strong>Job title:</strong>
</div>
<div class="col-md-10">
  <br/><%= @job.job_title.capitalize %>
</div>

<div class="col-md-2">
  <br/><strong>Job description:</strong>
</div>
<div class="col-md-10">
  <br/><%= @job.job_description.capitalize %>
</div>

<div class="col-md-2">
  <br/><strong>Industry:</strong>
</div>
<div class="col-md-10">
  <br/><%= @job.industry.capitalize %>
</div>

<div class="col-md-2">
  <br/><strong>Status:</strong>
</div>
<div class="col-md-10">
  <% if @job.status == true %>
  <br/><%= "Open "%>
  <% else %>
  <br/><%= "Closed "%>
  <% end %>
</div>

<div class="col-md-12">
<% if current_user.is_biz %>
<br/><%= link_to 'Edit', edit_job_path(@job), class: "btn btn-primary" %>
<% end %>
<% if current_user.is_seeker %>
<br/><%= link_to 'Apply', application_path, method: :post, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
<% end %>
</div>

app/views/jobs/show_public.html.erb
<div class="page-header">
  <h1><%= @job.job_title.capitalize %> @ <%= @job.company_name.capitalize %></h1>
</div>

<div class="col-md-2">
  <br/><strong>Job Title:</strong>
</div>
<div class="col-md-10">
  <br/><%= @job.job_title.capitalize %>
</div>

<div class="col-md-2">
  <br/><strong>Company Name:</strong>
</div>
<div class="col-md-10">
  <br/><%= @job.company_name.capitalize %>
</div>

<div class="col-md-2">
  <br/><strong>Job Description:</strong>
</div>
<div class="col-md-10">
  <br/><%= @job.job_description.capitalize %>
</div>

<div class="col-md-2">
  <br/><strong>Address:</strong>
</div>
<div class="col-md-10">
  <br/><%= @job.address.capitalize %>
</div>

<div class="col-md-2">
  <br/><strong>Industry:</strong>
</div>
<div class="col-md-10">
  <br/><%= @job.industry.capitalize %>
</div>

<div class="col-md-2">
  <br/><strong>Hourly Wage:</strong>
</div>
<div class="col-md-10">
  <br/>$<%= @job.wage_per_hour %>0
</div>

<div class="col-md-2">
  <br/><strong>Status:</strong>
</div>
<div class="col-md-10">
  <% if @job.status == true %>
  <br/><%= "Open "%>
  <% else %>
  <br/><%= "Closed "%>
  <% end %>
</div>