config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'

  get "job/:id" => "jobs#show_public", as: "show_job"

  post "applications/:id" => "applications#create"
  get "application/edit/:id" => "applications#edit", as: "application_approval"
  get "jobs/bizowner" => "jobs#bizowner"

  # AUTHENTICATION
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  # Users - custom routes for users, registration, profile, editing etc
  get "register" => "users#new"
  post "users" => "users#create"
  get "profile" => "users#show"
  get "profile/edit" => "users#edit"
  put "profile" => "users#update"
  patch "profile" => "users#update"
  patch "users/:id" => "users#update"
  resources :users, only: [:index, :destroy] do
    patch 'admin' => "users#toggle_admin", on: :member
  end

  # Jobseekers - custom routes for job seekers
  get "jobseeker/register-profile" => "jobseekers#new"
  post "jobseeker" => "jobseekers#create"
  get "jobseeker/profile/edit" => "jobseekers#edit", as: "edit_job_profile"
  get "jobseeker/profile/:id" => "jobseekers#show_public", as: "show_seeker"
  get "jobseeker/profile" => "jobseekers#show"
  put "jobseeker/:id" => "jobseekers#update"
  patch "jobseeker.:id" => "jobseekers#update"

  # Bizowners - custom routes for biz owners
  get "business/register-profile" => "bizowners#new", as: "bizowner_register"
  post "bizowners" => "bizowners#create"
  get "business/edit" => "bizowners#edit"
  get "business/profile/:id" => "bizowners#show_public", as: "show_business"
  get "business/profile" => "bizowners#show"
  put "business/profile" => "bizowners#update"
  patch "business/profile" => "bizowners#update"
  post "business/profile" => "bizowners#update"

  resources :jobseekers_reviews
  resources :bizowners_reviews
  resources :applications
  resources :users
  resources :bizowners
  resources :jobs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
    belongs_to :job
    belongs_to :jobseeker
    has_one :bizowners_review
    has_one :jobseekers_review

    #VALIDATIONS
    validates :job_id,
    uniqueness: {scope: :jobseeker_id}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bizowner.rb
class Bizowner < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :bizowners_reviews, dependent: :destroy
  has_many :jobseekers_reviews, dependent: :destroy
  has_many :jobs

  #VALIDATIONS
  validates :user_id,
  uniqueness: true
end

app/models/bizowners_review.rb
class BizownersReview < ApplicationRecord
  belongs_to :bizowner, dependent: :destroy
  belongs_to :jobseeker, dependent: :destroy
  belongs_to :application, dependent: :destroy
end

app/models/job.rb
class Job < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
  belongs_to :bizowner
  has_many :applications, dependent: :destroy

  #VALIDATIONS
  validates :bizowner_id,
  presence: true

  before_save :downcase_fields

  def downcase_fields
    self.company_name.downcase!
    self.job_title.downcase!
    self.job_description.downcase!
    self.address.downcase!
    self.industry.downcase!
  end

  def self.search(search,type)
    if search
      case type
      when "address"
        where('address LIKE ?', "%#{search}%")
      when "company_name"
        where('company_name LIKE ?', "%#{search}%")
      when "job_title"
        where('job_title LIKE ?', "%#{search}%")
      else
        scoped
      end
    else
      all
    end
  end
end

app/models/jobseeker.rb
class Jobseeker < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :applications, dependent: :destroy
  has_many :bizowners_reviews, dependent: :destroy
  has_many :jobseekers_reviews, dependent: :destroy

  #VALIDATIONS
  validates :user_id,
  uniqueness: true
end

app/models/jobseekers_review.rb
class JobseekersReview < ApplicationRecord
  belongs_to :bizowner, dependent: :destroy
  belongs_to :jobseeker, dependent: :destroy
  belongs_to :application, dependent: :destroy
end

app/models/listing.rb
class Listing < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
  geocoded_by :address
after_validation :geocode
belongs_to :bizowner
has_many :applications, dependent: :destroy

def self.search(search,type)
  if search

    case type
    when "name"
      where('name LIKE ?', "%#{search}%")
    when "address"
      where('address LIKE ?', "%#{search}%")
    when "title"
      where('title LIKE ?', "%#{search}%")
    end
  else
    all
  end
end
end

app/models/user.rb
class User < ApplicationRecord
  #ASSOCIATIONS
  has_one :jobseeker
  has_one :bizowner

  # CONSTANTS
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # MIXINS
  has_secure_password

  # VALIDATIONS
  validates :first_name,
  presence: true,
  length: { in: 3..50 }

  validates :last_name,
  presence: true,
  length: { in: 3..50 }

  validates :email,
  presence: true,
  length: { maximum: 255 },
  uniqueness: {case_sensitive: false},
  format: VALID_EMAIL_REGEX

  validates :password, length: { in: 8..72 } , on: :create, :if => :password_needs_validating?

  # custom method to ensure we have atleast one admin user
  validate :atleast_one_admin

  # HOOKS
  before_save :downcase_fields

  # PUBLIC METHODS
  def name
    "#{first_name.titlecase} #{last_name.titlecase}"
  end

  def self.authenticate(params)
    User.find_by_email(params[:email]).try(:authenticate, params[:password])
  end

  # PRIVATE METHODS
  private

  def atleast_one_admin
    if is_admin == false && User.where(:is_admin => true).count < 2
      errors.add(:base, "There must be at least 1 admin user")
    end
  end

  def password_needs_validating?
    if new_record? || password.present?
      true
    else
      false
    end
  end

  def downcase_fields
    self.email = email.downcase
    self.first_name = first_name.downcase
    self.last_name = last_name.downcase
  end


end

app/helpers/bizowner_helper.rb
module BizownerHelper
end

app/helpers/bizowners_helper.rb
module BizownersHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
end
end

app/helpers/jobseeker_helper.rb
module JobseekerHelper
end

app/helpers/jobseekers_helper.rb
module JobseekersHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
  def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/partials/_footer.html.erb
<script src="https://use.fontawesome.com/c80368376f.js"></script>

<footer class="footer-distributed">

<div class ="container">
			<div class="footer-left">

				<h3 class="ourbrand"><b>Jobs <i>Lite</i></b></span></h3>

				<p class="footer-links">
					<a href="#">Home</a>
					·
					<a href="#">Blog</a>
					·
					<a href="#">Pricing</a>
					·
					<a href="#">About</a>
					·
					<a href="#">Faq</a>
					·
					<a href="#">Contact</a>
				</p>

				<p class="footer-company-name">Company Name &copy; 2016</p>
		</div>

		<div class="footer-center">
			<div>
				<i class="fa fa-map-marker"></i>
				<p><span>#03-01, 8 Claymore Hill </span> Orchard, Singapore</p>
			</div>
			<div>
				<i class="fa fa-phone"></i>
				<p>+65 258 2111</p>
			</div>
			<div>
				<i class="fa fa-envelope"></i>
				<p><a href="mailto:support@company.com">jobslitesg@gmail.com</a></p>
			</div>
		</div>

		<div class="footer-right">
			<p class="footer-company-about">
				<span>About the company</span>
				Mobile First Designed Website to accelerate the part-time recruitment process for both job-seeker and employer.
			</p>
			<div class="footer-icons">
				<a href="#"><i class="fa fa-facebook-square"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-linkedin"></i></a>
				<a href="#"><i class="fa fa-github"></i></a>
			</div>
		</div>

	</div>
</footer>

app/views/partials/_header.html.erb
<nav id ="main_nav_bar" class="navbar navbar-default navbar-fixed-top">
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
    &#9776;
  </button>
  <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
  <div class="container">
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link ourbrand" href="/"><b>Jobs <i>Lite</i></b> <span class="sr-only">(current)</span></a>
    </li>
    <% if current_user.present? %>
    <% if current_user.is_seeker %>
    <li class="nav-item">
      <%= link_to 'Following', jobs_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Applications", applications_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Post Review", jobseekers_reviews_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Help', jobs_path, class: "nav-link" %>
    </li>
    <% end %>
    <% if current_user.is_biz %>
    <li class="nav-item">
      <%= link_to 'Your Followers', jobs_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Post A Job", new_job_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Applicants", applications_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Post Review', bizowners_reviews_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Help', jobs_path, class: "nav-link" %>
    </li>
    <% end %>
    <li class="nav-item pull-xs-right">
      <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
    </li>
    <% if current_user.is_admin %>
    <li class="nav-item pull-xs-right">
      <%= link_to "Manage Users", users_path, class: "nav-link" %>
    </li>
    <% end %>
    <li class="nav-item pull-xs-right">
      <%= link_to "#{current_user.name}", profile_path, class: "nav-link"%>
    </li>
    <% else %>
     <!-- <ul class="nav navbar-nav navbar-left"> -->
    <li class="nav-item">
      <%= link_to 'Followers', jobs_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'All Jobs', jobs_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Help', jobs_path, class: "nav-link" %>
    </li>
    <li class="nav-item pull-xs-right">
      <%= link_to 'Login', login_path, id: "nav-link-login", class: "nav-link" %>
    </li>
    <li class="nav-item pull-xs-right">
      <%= link_to 'Register', register_path, class: "nav-link" %>
    </li>
  <!-- </ul> -->

    <% end %>

  </ul>
  </div>
  </div>
</nav>