config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'

  get "job/:id" => "jobs#show_public", as: "show_job"

  post "applications/:id" => "applications#create"
  get "application/edit/:id" => "applications#edit", as: "application_approval"
  get "jobs/bizowner" => "jobs#bizowner"

  # AUTHENTICATION
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  # Users - custom routes for users, registration, profile, editing etc
  get "register" => "users#new"
  post "users" => "users#create"
  get "profile" => "users#show"
  get "profile/edit" => "users#edit"
  put "profile" => "users#update"
  patch "profile" => "users#update"
  patch "users/:id" => "users#update"
  resources :users, only: [:index, :destroy] do
    patch 'admin' => "users#toggle_admin", on: :member
  end

  # Jobseekers - custom routes for job seekers
  get "jobseeker/register-profile" => "jobseekers#new"
  post "jobseeker" => "jobseekers#create"
  get "jobseeker/profile/edit" => "jobseekers#edit", as: "edit_job_profile"
  get "jobseeker/profile/:id" => "jobseekers#show_public", as: "show_seeker"
  get "jobseeker/profile" => "jobseekers#show"
  put "jobseeker/:id" => "jobseekers#update"
  patch "jobseeker.:id" => "jobseekers#update"

  # Bizowners - custom routes for biz owners
  get "business/register-profile" => "bizowners#new", as: "bizowner_register"
  post "bizowners" => "bizowners#create"
  get "business/edit" => "bizowners#edit"
  get "business/profile/:id" => "bizowners#show_public", as: "show_business"
  get "business/profile" => "bizowners#show"
  put "business/profile" => "bizowners#update"
  patch "business/profile" => "bizowners#update"
  post "business/profile" => "bizowners#update"

  resources :jobseekers_reviews
  resources :bizowners_reviews
  resources :applications
  resources :users
  resources :bizowners
  resources :jobs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  #ASSOCIATIONS
  has_one :jobseeker
  has_one :bizowner

  # CONSTANTS
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # MIXINS
  has_secure_password

  # VALIDATIONS
  validates :first_name,
  presence: true,
  length: { in: 3..50 }

  validates :last_name,
  presence: true,
  length: { in: 3..50 }

  validates :email,
  presence: true,
  length: { maximum: 255 },
  uniqueness: {case_sensitive: false},
  format: VALID_EMAIL_REGEX

  validates :password, length: { in: 8..72 } , on: :create, :if => :password_needs_validating?

  # custom method to ensure we have atleast one admin user
  validate :atleast_one_admin

  # HOOKS
  before_save :downcase_fields

  # PUBLIC METHODS
  def name
    "#{first_name.titlecase} #{last_name.titlecase}"
  end

  def self.authenticate(params)
    User.find_by_email(params[:email]).try(:authenticate, params[:password])
  end

  # PRIVATE METHODS
  private

  def atleast_one_admin
    if is_admin == false && User.where(:is_admin => true).count < 2
      errors.add(:base, "There must be at least 1 admin user")
    end
  end

  def password_needs_validating?
    if new_record? || password.present?
      true
    else
      false
    end
  end

  def downcase_fields
    self.email = email.downcase
    self.first_name = first_name.downcase
    self.last_name = last_name.downcase
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :is_authenticated, except: [:new, :create]
  before_action :is_authenticated_admin, only: [:index, :destroy, :toggle_admin]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        if @user.is_seeker
          @user.update(is_biz: false)
        elsif !@user.is_seeker
          @user.update(is_biz: true)
        end
        session[:user_id] = @user.id
        format.html {
          if @user.is_seeker
            redirect_to jobseeker_register_profile_path, notice: "Let's create your job profile!"
          else
            redirect_to bizowner_register_path, notice: "Let's create your business profile!"
          end }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

      # PATCH/PUT /users/1
      # PATCH/PUT /users/1.json
      def update
        respond_to do |format|
          if @user.update(edit_user_params)
            format.html { render :show, notice: 'User was successfully updated.' }
            format.json { render :show, status: :ok, location: @user }
          else
            format.html { render :edit }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /users/1
      # DELETE /users/1.json
      def destroy
        @user.destroy
        respond_to do |format|
          format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      # PATCH/PUT  /users/1/admin
      def toggle_admin
        @user.is_admin = !@user.is_admin
        if @user.save
          redirect_to users_url, notice: "User #{@user.name} Admin status is: #{@user.is_admin?}"
        else
          redirect_to users_url, notice: "Error setting admin status: #{@user.errors.full_messages.first}"
        end
      end


    def update
      respond_to do |format|
        if @user.update(edit_user_params)
          format.html { render :show, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    # PATCH/PUT  /users/1/admin
    def toggle_admin
      @user = User.find(params[:id])
      @user.is_admin = !@user.is_admin
      if @user.save
        redirect_to users_url, notice: "User #{@user.name} Admin status is: #{@user.is_admin?}"
      else
        redirect_to users_url, notice: "Error setting admin status: #{@user.errors.full_messages.first}"
      end
    end

  private
  # Use callbacks to share common setup or constraints between actions.
  # What does set_user do?
  def set_user
    @user = User.find(session[:user_id])
    if current_user.is_seeker
      @jobseeker = Jobseeker.find_by(user_id: current_user.id)
    end
    if current_user.is_biz
      @bizowner = Bizowner.find_by(user_id: current_user.id)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name , :email, :password, :contact, :is_seeker)
  end

  def edit_user_params
    params.require(:user).permit(:first_name, :last_name , :email, :contact)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= form_for(user, html: { class: "form-horizontal", role: "form" })  do |f| %>
<% if user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :first_name, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :first_name, class: "form-control"  %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :last_name, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :last_name, class: "form-control"  %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :email, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :email, class: "form-control"  %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :contact, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.number_field :contact, class: "form-control"  %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :user_type, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <% if @user.is_admin %>
    <%= "Admin"%>
    <% elsif @user.is_seeker %>
    <%= "Job Seeker" %>
    <% else %>
    <%= "Business Owner" %>
    <% end %>
  </div>
</div>
<br/>

<div class="form-group">
  <div class="col-md-12">
    <br><%= f.submit class: "btn btn-primary" %>
  </div>
</div>

<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, html: { class: "form-horizontal", role: "form" }) do |f| %>
<% if user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :first_name, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :first_name, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :last_name, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :last_name, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :email, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :email, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :password, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.password_field :password, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :contact, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.number_field :contact, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :type, class: "col-md-2 control-label" %>
  <div class="col-md-2">
    <%= f.radio_button :is_seeker, "true"%>
    <%= label :is_seeker, "Job Seeker"%>
  </div>
  <div class="col-md-2">
    <%= f.radio_button :is_seeker, "false"%>
    <%= label :is_seeker, "Business Owner"%>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-md-10">
    <br><%= f.submit class: "btn btn-primary"%>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<p id="notice"><%= notice %></p>

<%= render 'edit_form', user: @user %>
<div class="col-md-12">
  <br/>
  <%= link_to 'Show Profile', profile_path %> |
  <% if @user.is_seeker %>
  <%= link_to 'Edit Job Profile', edit_job_profile_path %>
  <% elsif @user.is_biz %>
  <%= link_to 'Edit Business Profile', business_edit_path %>
  <% end %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact</th>
      <th>Email</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.contact %></td>
        <td><%= user.email %></td>
        <td><% if user.is_seeker%>
            <%= "Job Seeker"%>
            <% else %>
            <%= "Business Owner" %>
            <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', profile_edit_path(user) %></td>
        <td><%= link_to "#{user.is_admin?}", admin_user_path(user), method: :patch %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', register_path %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<div class="col-md-2">
  <br/><strong>Name:</strong>
</div>
<div class="col-md-10">
  <br/><%= @user.name %>
</div>

<div class="col-md-2">
  <br/><strong>Contact:</strong>
</div>
<div class="col-md-10">
  <br/><%= @user.contact %>
</div>


<div class="col-md-2">
  <br/><strong>Email:</strong>
</div>
<div class="col-md-10">
  <br/><%= @user.email %>
</div>

<% if @user.is_seeker %>

<div class="col-md-2">
  <br/><strong>Date of Birth:</strong>
</div>
<div class="col-md-10">
  <br/><%= @jobseeker.dob %>
</div>

<div class="col-md-2">
  <br/><strong>Postal code:</strong>
</div>
<div class="col-md-10">
  <br/><%= @jobseeker.postal_code %>
</div>


<div class="col-md-2">
  <br/><strong>Highest Qualification:</strong>
</div>
<div class="col-md-10">
  <br/><%= @jobseeker.highest_qualification %>
</div>


<div class="col-md-2">
  <br/><strong>Preferred Area:</strong>
</div>
<div class="col-md-10">
  <br/><%= @jobseeker.preferred_area %>
</div>

<div class="col-md-2">
  <br/><strong>Preferred Location:</strong>
</div>
<div class="col-md-10">
  <br/><%= @jobseeker.preferred_location %>
</div>

<div class="col-md-2">
  <br/><strong>Description:</strong>
</div>
<div class="col-md-10">
  <br/><%= @jobseeker.description %>
</div>

<div class="col-md-2">
  <br/><strong>Wage:</strong>
</div>
<div class="col-md-10">
  <br/><%= @jobseeker.wage %>
</div>

<div class="col-md-2">
  <br/><strong>Start date:</strong>
</div>
<div class="col-md-10">
  <br/><%= @jobseeker.start_date %>
</div>

<div class="col-md-2">
  <br/><strong>End date:</strong>
</div>
<div class="col-md-10">
  <br/><%= @jobseeker.end_date %>
</div>

<% elsif @user.is_biz %>
<div class="col-md-2">
  <br/><strong>Company:</strong>
</div>
<div class="col-md-10">
  <br/><%= @bizowner.name %>
</div>

<div class="col-md-2">
  <br/><strong>Description:</strong>
</div>
<div class="col-md-10">
  <br/><%= @bizowner.description %>
</div>

<div class="col-md-2">
  <br/><strong>Business Address:</strong>
</div>
<div class="col-md-10">
  <br/><%= @bizowner.address %>
</div>

<div class="col-md-2">
  <br/><strong>Postal Code</strong>
</div>
<div class="col-md-10">
  <br/><%= @bizowner.postal_code %>
</div>

<div class="col-md-2">
  <br/><strong>License:</strong>
</div>
<div class="col-md-10">
  <br/><%= @bizowner.license_number %>
</div>

<% end %>

<div class="col-md-2">
  <br/><strong>User Type:</strong>
</div>
<div class="col-md-10">
  <% if @user.is_admin %>
  <br/><%= "Admin" %>
  <% elsif @user.is_seeker %>
  <br/><%= "Job Seeker" %>
  <% else %>
  <br/><%= "Business Owner" %>
  <% end %>
</div>

<div class="col-md-12">
<br/><%= link_to 'Edit User Profile', profile_edit_path %> |
<% if @user.is_seeker %>
<%= link_to 'Edit Job Profile', edit_job_profile_path %>
<% elsif @user.is_biz %>
<%= link_to 'Edit Business Profile', business_edit_path %>
<% end %>
</div>