config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'

  get "job/:id" => "jobs#show_public", as: "show_job"

  post "applications/:id" => "applications#create"
  get "application/edit/:id" => "applications#edit", as: "application_approval"
  get "jobs/bizowner" => "jobs#bizowner"

  # AUTHENTICATION
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  # Users - custom routes for users, registration, profile, editing etc
  get "register" => "users#new"
  post "users" => "users#create"
  get "profile" => "users#show"
  get "profile/edit" => "users#edit"
  put "profile" => "users#update"
  patch "profile" => "users#update"
  patch "users/:id" => "users#update"
  resources :users, only: [:index, :destroy] do
    patch 'admin' => "users#toggle_admin", on: :member
  end

  # Jobseekers - custom routes for job seekers
  get "jobseeker/register-profile" => "jobseekers#new"
  post "jobseeker" => "jobseekers#create"
  get "jobseeker/profile/edit" => "jobseekers#edit", as: "edit_job_profile"
  get "jobseeker/profile/:id" => "jobseekers#show_public", as: "show_seeker"
  get "jobseeker/profile" => "jobseekers#show"
  put "jobseeker/:id" => "jobseekers#update"
  patch "jobseeker.:id" => "jobseekers#update"

  # Bizowners - custom routes for biz owners
  get "business/register-profile" => "bizowners#new", as: "bizowner_register"
  post "bizowners" => "bizowners#create"
  get "business/edit" => "bizowners#edit"
  get "business/profile/:id" => "bizowners#show_public", as: "show_business"
  get "business/profile" => "bizowners#show"
  put "business/profile" => "bizowners#update"
  patch "business/profile" => "bizowners#update"
  post "business/profile" => "bizowners#update"

  resources :jobseekers_reviews
  resources :bizowners_reviews
  resources :applications
  resources :users
  resources :bizowners
  resources :jobs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bizowner.rb
class Bizowner < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :bizowners_reviews, dependent: :destroy
  has_many :jobseekers_reviews, dependent: :destroy
  has_many :jobs

  #VALIDATIONS
  validates :user_id,
  uniqueness: true
end

app/controllers/bizowners_controller.rb
class BizownersController < ApplicationController
  before_action :is_authenticated
  before_action :set_bizowner, only: [:edit, :show]

  def new
    @bizowner = Bizowner.new
  end

  def create
    @bizowner = Bizowner.new(biz_params)
    @bizowner.update(user_id: current_user.id)
    respond_to do |format|
      if @bizowner.save
        format.html { redirect_to profile_path,notice: "Business Profile has been successfully created!" }
        format.json { render :show, status: :created, location: @bizowner }
      else
        format.html { render :new }
        format.json { render json: @bizowner.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @bizowner = Bizowner.find_by(user_id: current_user.id)
  end

  def show_public
    @bizowner = Bizowner.find_by(id: params[:id])
  end

  def destroy
    @bizowner.destroy
    respond_to do |format|
      format.html { redirect_to bizowners_url, notice: 'Business Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
    @bizowner = Bizowner.find_by(user_id: current_user.id)
  end

  def update
    @bizowner = Bizowner.find_by(user_id: current_user.id)
    respond_to do |format|
      if @bizowner.update(biz_params)
        format.html { redirect_to profile_path, notice: 'Business Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @bizowner }
      else
        format.html { render :edit }
        format.json { render json: @bizowner.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_bizowner
    @bizowner = Bizowner.find_by(user_id: current_user.id)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def biz_params
    params.require(:bizowner).permit(:name, :description , :license_number, :postal_code, :address)
  end

end

app/helpers/bizowner_helper.rb
module BizownerHelper
end

app/helpers/bizowners_helper.rb
module BizownersHelper
end

app/views/bizowners/_form.html.erb
<%= form_for(@bizowner, html: { class: "form-horizontal", role: "form" }) do |f| %>
<% if bizowner.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(bizowner.errors.count, "error") %> prohibited this bizowner from being saved:</h2>

  <ul>
    <% bizowner.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :company_name, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :name, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :company_profile, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_area :description, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :company_address, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :address, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :postal_code, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :postal_code, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <%= f.label :ACRA_registration_number, class: "col-md-2 control-label" %>
  <div class="col-md-10">
    <%= f.text_field :license_number, class: "form-control" %><br>
  </div>
</div>

<div class="form-group">
  <div class="col-md-12">
    <br><%= f.submit class: "btn btn-primary" %>
  </div>
</div>

<% end %>

app/views/bizowners/edit.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form', bizowner: @bizowner %>

<div class="col-md-12">
  <br/>
  <%= link_to 'Show User Profile', profile_path %> |
  <%= link_to 'Edit User Profile', profile_edit_path %>
</div>

app/views/bizowners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bizowners</h1>

<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bizowners.each do |bizowner| %>
      <tr>
        <td><%= bizowner.name %></td>
        <td><%= bizowner.description %></td>
        <td><%= link_to 'Show', bizowner %></td>
        <td><%= link_to 'Edit', edit_bizowner_path(bizowner) %></td>
        <td><%= link_to 'Destroy', bizowner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<br>

<%= link_to 'New Bizowner', new_bizowner_path %>

app/views/bizowners/new.html.erb
<%= render 'form', bizowner: @bizowner %>

app/views/bizowners/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Company:</strong>
  <%= @bizowner.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bizowner.description %>
</p>

<p>
  <strong>Business Address:</strong>
  <%= @bizowner.address %>
</p>

<p>
  <strong>Postal Code</strong>
  <%= @bizowner.postal_code %>
</p>

<p>
  <strong>License:</strong>
  <%= @bizowner.license_number %>
</p>

<%= link_to 'Show User Profile', profile_path %> |
<%= link_to 'Edit User Profile', profile_edit_path %> |
<%= link_to 'Edit Business Profile', business_edit_path %>

app/views/bizowners/show_public.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @bizowner.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bizowner.description %>
</p>

<p>
  <strong>Business Address:</strong>
  <%= @bizowner.address %>
</p>

<p>
  <strong>Postal Code</strong>
  <%= @bizowner.postal_code %>
</p>

<p>
  <strong>License:</strong>
  <%= @bizowner.license_number %>
</p>